In [1]:
#Introduccion al pandas
import pandas as pd

In [2]:
df = pd.read_csv("base_datos_2008.csv", nrows = 100000)

In [3]:
df.head(10) #Muestra las 10 primeras filas

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   
5  2008      1           3          4   1940.0        1915   2121.0   
6  2008      1           3          4   1937.0        1830   2037.0   
7  2008      1           3          4   1039.0        1040   1132.0   
8  2008      1           3          4    617.0         615    652.0   
9  2008      1           3          4   1620.0        1620   1639.0   

   CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0        2225            WN        335  ...    4.0      8.0          0   
1        1000            WN       3231  ...    5.0     10.0          0   
2         750            WN        448  ...    3.0     17.0          0   
3        1100            WN       1746  ...    3.0      7.0          0   
4        1925            WN       3920  ...    3.0     10.0          0   
5        2110            WN        378  ...    4.0     10.0          0   
6        1940            WN        509  ...    3.0      7.0          0   
7        1150            WN        535  ...    7.0      7.0          0   
8         650            WN         11  ...    6.0     19.0          0   
9        1655            WN        810  ...    3.0      6.0          0   

   CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0               NaN         0           NaN          NaN      NaN   
1               NaN         0           NaN          NaN      NaN   
2               NaN         0           NaN          NaN      NaN   
3               NaN         0           NaN          NaN      NaN   
4               NaN         0           2.0          0.0      0.0   
5               NaN         0           NaN          NaN      NaN   
6               NaN         0          10.0          0.0      0.0   
7               NaN         0           NaN          NaN      NaN   
8               NaN         0           NaN          NaN      NaN   
9               NaN         0           NaN          NaN      NaN   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4            0.0               32.0  
5            NaN                NaN  
6            0.0               47.0  
7            NaN                NaN  
8            NaN                NaN  
9            NaN                NaN  

[10 rows x 29 columns]

In [4]:
df.tail() #Muestra las ultimas 5 columnas

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
99995  2008      1          25          5   2204.0        1935    106.0   
99996  2008      1          26          6   1933.0        1935   2234.0   
99997  2008      1          27          7   2047.0        1935   2400.0   
99998  2008      1          28          1   1956.0        1935   2308.0   
99999  2008      1          29          2   1938.0        1935   2308.0   

       CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
99995        2257            XE       7676  ...    4.0     17.0          0   
99996        2257            XE       7676  ...    4.0     16.0          0   
99997        2257            XE       7676  ...    6.0     18.0          0   
99998        2257            XE       7676  ...    5.0     25.0          0   
99999        2257            XE       7676  ...    5.0     41.0          0   

       CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
99995               NaN         0           0.0          0.0      0.0   
99996               NaN         0           NaN          NaN      NaN   
99997               NaN         0          23.0          0.0      0.0   
99998               NaN         0           NaN          NaN      NaN   
99999               NaN         0           NaN          NaN      NaN   

       SecurityDelay  LateAircraftDelay  
99995            0.0              129.0  
99996            NaN                NaN  
99997            0.0               40.0  
99998            NaN                NaN  
99999            NaN                NaN  

[5 rows x 29 columns]

In [5]:
df.columns #Muestra las columnas que tiene el data set

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [6]:
df.dtypes #Muestra los tipos de variable que tiene el data set

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier         object
FlightNum              int64
TailNum               object
ActualElapsedTime    float64
CRSElapsedTime         int64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin                object
Dest                  object
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode      object
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [7]:
df.values #Muestra todo los datos que se tiene

array([[2008, 1, 3, ..., nan, nan, nan],
       [2008, 1, 3, ..., nan, nan, nan],
       [2008, 1, 3, ..., nan, nan, nan],
       ...,
       [2008, 1, 27, ..., 0.0, 0.0, 40.0],
       [2008, 1, 28, ..., nan, nan, nan],
       [2008, 1, 29, ..., nan, nan, nan]], dtype=object)

FILTRAR DATOS

In [9]:
df["ArrDelay"].head() #Muestra los primeros datos de la columna "Arrdelay"

0   -14.0
1     2.0
2    14.0
3    -6.0
4    34.0
Name: ArrDelay, dtype: float64

In [10]:
df[0:10] #Ver datos de la fila 0 a la fila 100

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   
5  2008      1           3          4   1940.0        1915   2121.0   
6  2008      1           3          4   1937.0        1830   2037.0   
7  2008      1           3          4   1039.0        1040   1132.0   
8  2008      1           3          4    617.0         615    652.0   
9  2008      1           3          4   1620.0        1620   1639.0   

   CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0        2225            WN        335  ...    4.0      8.0          0   
1        1000            WN       3231  ...    5.0     10.0          0   
2         750            WN        448  ...    3.0     17.0          0   
3        1100            WN       1746  ...    3.0      7.0          0   
4        1925            WN       3920  ...    3.0     10.0          0   
5        2110            WN        378  ...    4.0     10.0          0   
6        1940            WN        509  ...    3.0      7.0          0   
7        1150            WN        535  ...    7.0      7.0          0   
8         650            WN         11  ...    6.0     19.0          0   
9        1655            WN        810  ...    3.0      6.0          0   

   CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0               NaN         0           NaN          NaN      NaN   
1               NaN         0           NaN          NaN      NaN   
2               NaN         0           NaN          NaN      NaN   
3               NaN         0           NaN          NaN      NaN   
4               NaN         0           2.0          0.0      0.0   
5               NaN         0           NaN          NaN      NaN   
6               NaN         0          10.0          0.0      0.0   
7               NaN         0           NaN          NaN      NaN   
8               NaN         0           NaN          NaN      NaN   
9               NaN         0           NaN          NaN      NaN   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4            0.0               32.0  
5            NaN                NaN  
6            0.0               47.0  
7            NaN                NaN  
8            NaN                NaN  
9            NaN                NaN  

[10 rows x 29 columns]

In [11]:
df[df["ArrDelay"] <= 60].head() #Muestra vuelos retrasados menos de 60 secs

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0        2225            WN        335  ...    4.0      8.0          0   
1        1000            WN       3231  ...    5.0     10.0          0   
2         750            WN        448  ...    3.0     17.0          0   
3        1100            WN       1746  ...    3.0      7.0          0   
4        1925            WN       3920  ...    3.0     10.0          0   

   CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0               NaN         0           NaN          NaN      NaN   
1               NaN         0           NaN          NaN      NaN   
2               NaN         0           NaN          NaN      NaN   
3               NaN         0           NaN          NaN      NaN   
4               NaN         0           2.0          0.0      0.0   

   SecurityDelay  LateAircraftDelay  
0            NaN                NaN  
1            NaN                NaN  
2            NaN                NaN  
3            NaN                NaN  
4            0.0               32.0  

[5 rows x 29 columns]

In [12]:
df[pd.isna(df["ArrDelay"])].head() #Muestra las 5 primeras columnas donde no hay datos en la columna ArrDelay

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
178  2008      1           3          4      NaN         700      NaN   
373  2008      1           3          4      NaN        1100      NaN   
399  2008      1           3          4      NaN         905      NaN   
401  2008      1           3          4      NaN        1620      NaN   
415  2008      1           3          4      NaN        1930      NaN   

     CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
178         830            WN        126  ...    NaN      NaN          1   
373        1215            WN       1146  ...    NaN      NaN          1   
399        1025            WN        469  ...    NaN      NaN          1   
401        1740            WN        618  ...    NaN      NaN          1   
415        2035            WN       2528  ...    NaN      NaN          1   

     CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
178                 A         0           NaN          NaN      NaN   
373                 A         0           NaN          NaN      NaN   
399                 A         0           NaN          NaN      NaN   
401                 C         0           NaN          NaN      NaN   
415                 A         0           NaN          NaN      NaN   

     SecurityDelay  LateAircraftDelay  
178            NaN                NaN  
373            NaN                NaN  
399            NaN                NaN  
401            NaN                NaN  
415            NaN                NaN  

[5 rows x 29 columns]

In [13]:
len([pd.isna(df["ArrDelay"])])

1

TRANSFORMACIONES DE LA BASE DE DATOS

In [14]:
#Crear nueva columna
df["HoursDelay"] = round(df["ArrDelay"] / 60)

In [15]:
df["HoursDelay"].head()

0   -0.0
1    0.0
2    0.0
3   -0.0
4    1.0
Name: HoursDelay, dtype: float64

In [16]:
del(df["HoursDelay"]) #Borra una columna de la base de datos

In [17]:
df = df.drop(["Diverted", "Cancelled", "Year"], axis=1) #Borra varias columnas

In [18]:
df.drop(0) #Elimina la fila 0

Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  CRSArrTime  \
1          1           3          4    754.0         735   1002.0        1000   
2          1           3          4    628.0         620    804.0         750   
3          1           3          4    926.0         930   1054.0        1100   
4          1           3          4   1829.0        1755   1959.0        1925   
5          1           3          4   1940.0        1915   2121.0        2110   
...      ...         ...        ...      ...         ...      ...         ...   
99995      1          25          5   2204.0        1935    106.0        2257   
99996      1          26          6   1933.0        1935   2234.0        2257   
99997      1          27          7   2047.0        1935   2400.0        2257   
99998      1          28          1   1956.0        1935   2308.0        2257   
99999      1          29          2   1938.0        1935   2308.0        2257   

      UniqueCarrier  FlightNum TailNum  ...  Dest  Distance  TaxiIn  TaxiOut  \
1                WN       3231  N772SW  ...   TPA       810     5.0     10.0   
2                WN        448  N428WN  ...   BWI       515     3.0     17.0   
3                WN       1746  N612SW  ...   BWI       515     3.0      7.0   
4                WN       3920  N464WN  ...   BWI       515     3.0     10.0   
5                WN        378  N726SW  ...   JAX       688     4.0     10.0   
...             ...        ...     ...  ...   ...       ...     ...      ...   
99995            XE       7676  N11181  ...   OKC       866     4.0     17.0   
99996            XE       7676  N16170  ...   OKC       866     4.0     16.0   
99997            XE       7676  N12167  ...   OKC       866     6.0     18.0   
99998            XE       7676  N16170  ...   OKC       866     5.0     25.0   
99999            XE       7676  N11176  ...   OKC       866     5.0     41.0   

       CancellationCode CarrierDelay WeatherDelay  NASDelay  SecurityDelay  \
1                   NaN          NaN          NaN       NaN            NaN   
2                   NaN          NaN          NaN       NaN            NaN   
3                   NaN          NaN          NaN       NaN            NaN   
4                   NaN          2.0          0.0       0.0            0.0   
5                   NaN          NaN          NaN       NaN            NaN   
...                 ...          ...          ...       ...            ...   
99995               NaN          0.0          0.0       0.0            0.0   
99996               NaN          NaN          NaN       NaN            NaN   
99997               NaN         23.0          0.0       0.0            0.0   
99998               NaN          NaN          NaN       NaN            NaN   
99999               NaN          NaN          NaN       NaN            NaN   

       LateAircraftDelay  
1                    NaN  
2                    NaN  
3                    NaN  
4                   32.0  
5                    NaN  
...                  ...  
99995              129.0  
99996                NaN  
99997               40.0  
99998                NaN  
99999                NaN  

[99999 rows x 26 columns]

GROUPBY

In [19]:
df.groupby(by = "DayOfWeek")["ArrDelay"].max() #Agrupa por cada dia de la semana un valor de los retrasos de los vuelos el maximo

DayOfWeek
1    431.0
2    360.0
3    422.0
4    486.0
5    364.0
6    500.0
7    367.0
Name: ArrDelay, dtype: float64

In [20]:
df.groupby(by = "DayOfWeek")["ArrDelay"].describe()

count       mean        std   min   25%  50%   75%    max
DayOfWeek                                                             
1          14349.0   4.568960  29.047008 -56.0  -9.0 -3.0   9.0  431.0
2          14471.0   0.446479  21.617710 -48.0 -10.0 -4.0   5.0  360.0
3          14504.0  -1.646511  18.464538 -48.0 -11.0 -5.0   3.0  422.0
4          16774.0  13.387922  38.490537 -45.0  -7.0  2.0  19.0  486.0
5          14350.0   7.684948  28.156892 -52.0  -7.0  0.0  14.0  364.0
6          11172.0   2.069280  27.866895 -49.0 -11.0 -4.0   6.0  500.0
7          13078.0  12.190625  41.925311 -57.0  -9.0  0.0  16.0  367.0

In [21]:
df.groupby(by = "DayOfWeek")["ArrDelay","DepDelay"].mean()

ArrDelay   DepDelay
DayOfWeek                      
1           4.568960   9.141704
2           0.446479   5.192300
3          -1.646511   3.680816
4          13.387922  16.511031
5           7.684948  12.067975
6           2.069280   8.080861
7          12.190625  17.135919

In [22]:
df.groupby(by = "DayOfWeek")["ArrDelay"].max() - df.groupby(by = "DayOfWeek")["ArrDelay"].min() #Rango de valores de cada dia de la semana

DayOfWeek
1    487.0
2    408.0
3    470.0
4    531.0
5    416.0
6    549.0
7    424.0
Name: ArrDelay, dtype: float64

In [23]:
dfATLHOU = df[df.Origin.isin(["ATL","HOU"])] #Cree un nuevo df 

In [24]:
dfATLHOU.groupby(by = ["DayOfWeek", "Origin"])["ArrDelay"].mean()

DayOfWeek  Origin
1          HOU        1.767764
2          HOU        1.624348
3          HOU        3.026178
4          HOU       21.047535
5          HOU        6.853448
6          HOU       -0.967172
7          HOU        7.842629
Name: ArrDelay, dtype: float64

TRATAR DUPLICADOS Y PERDIDOS

In [33]:
df = pd.read_csv("base_datos_2008.csv", nrows = 1e6) #Cargar un millon de datos

In [34]:
dfduplicate = df.append(df) #Genera una base de datos con datos duplicados

In [35]:
dfduplicate = dfduplicate.sample(frac=1)

In [36]:
dfclean= dfduplicate.drop_duplicates() #Borra duplicados

In [38]:
len(dfclean) == len(df)

False

In [37]:
len(dfclean)

999996

In [40]:
dfclean.drop_duplicates(subset = "DayofMonth") #Elimina los duplicados para una columna especifica

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
865547  2008      2          15          5   1249.0        1256   1346.0   
490162  2008      1          24          4   1832.0        1615   2001.0   
411871  2008      1           5          6    740.0         740    935.0   
767606  2008      2           2          6   1151.0         946   1311.0   
152813  2008      1           4          5   1255.0        1300   1418.0   
875413  2008      2          22          5   1443.0        1435   1927.0   
616967  2008      2           6          3   1046.0        1035   1143.0   
968117  2008      2          28          4   1807.0        1808   1858.0   
21363   2008      1           9          3    907.0         825   1016.0   
391203  2008      1          29          2   2040.0        2045   2135.0   
749525  2008      2           3          7    953.0        1005   1234.0   
147279  2008      1          26          6    600.0         600    652.0   
761125  2008      2          23          6      NaN         835      NaN   
150916  2008      1          31          4      NaN         903      NaN   
138229  2008      1          13          7    640.0         645    759.0   
755570  2008      2          14          4   1531.0        1532   1705.0   
197311  2008      1          18          5    758.0         800      NaN   
266313  2008      1           8          2    944.0         950   1207.0   
543795  2008      1          25          5   1603.0        1610   1919.0   
303748  2008      1          16          3    636.0         640    807.0   
317586  2008      1          27          7   2154.0        2135   2211.0   
186132  2008      1          11          5    643.0         650    755.0   
765872  2008      2           1          5   1106.0        1110   1203.0   
929680  2008      2          17          7   1238.0        1215   1507.0   
501036  2008      1           7          1   1550.0        1535   1838.0   
243685  2008      1          20          7   1314.0        1315   1559.0   
910309  2008      2          10          7   1335.0        1340   1613.0   
88527   2008      1          30          3    756.0         750   1215.0   
229940  2008      1          21          1   2151.0        2050   2340.0   
930681  2008      2          19          2   1603.0        1559   1649.0   
638534  2008      2          12          2   1214.0        1215   1558.0   

        CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
865547        1358            US       1965  ...    4.0     16.0          0   
490162        1735            AA        678  ...   11.0     21.0          0   
411871         935            MQ       4358  ...    4.0     14.0          0   
767606        1051            OO       6336  ...    5.0     11.0          0   
152813        1433            OH       5408  ...    5.0     11.0          0   
875413        1827            US         22  ...    4.0     27.0          0   
616967        1135            WN       1150  ...    4.0      7.0          0   
968117        1900            MQ       3246  ...    6.0      9.0          0   
21363          940            WN        723  ...    3.0      6.0          0   
391203        2145            MQ       3551  ...    2.0     11.0          0   
749525        1228            OH       5688  ...    4.0     17.0          0   
147279         651            YV       2639  ...    5.0     16.0          0   
761125        1116            OH       5457  ...    NaN      NaN          1   
150916         911            YV       7143  ...    NaN      NaN          1   
138229         815            YV       7343  ...    5.0     12.0          0   
755570        1706            OH       5043  ...   13.0     10.0          0   
197311         956            OO       5861  ...    NaN     20.0          0   
266313        1211            US        544  ...   15.0     19.0          0   
543795        1930            AS        801  ...    3.0     26.0          

Para datos faltantes o perdidos

In [42]:
df.dropna() #Borra los datos faltantes 

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, DepTime, CRSDepTime, ArrTime, CRSArrTime, UniqueCarrier, FlightNum, TailNum, ActualElapsedTime, CRSElapsedTime, AirTime, ArrDelay, DepDelay, Origin, Dest, Distance, TaxiIn, TaxiOut, Cancelled, CancellationCode, Diverted, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay]
Index: []

[0 rows x 29 columns]

In [44]:
df.dropna(subset= ['CancellationCode']) 

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
178     2008      1           3          4      NaN         700      NaN   
373     2008      1           3          4      NaN        1100      NaN   
399     2008      1           3          4      NaN         905      NaN   
401     2008      1           3          4      NaN        1620      NaN   
415     2008      1           3          4      NaN        1930      NaN   
...      ...    ...         ...        ...      ...         ...      ...   
999913  2008      2          11          1      NaN         855      NaN   
999919  2008      2          17          7      NaN         855      NaN   
999961  2008      2          17          7      NaN        1445      NaN   
999971  2008      2          22          5      NaN        1235      NaN   
999999  2008      2          17          7      NaN        1655      NaN   

        CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
178            830            WN        126  ...    NaN      NaN          1   
373           1215            WN       1146  ...    NaN      NaN          1   
399           1025            WN        469  ...    NaN      NaN          1   
401           1740            WN        618  ...    NaN      NaN          1   
415           2035            WN       2528  ...    NaN      NaN          1   
...            ...           ...        ...  ...    ...      ...        ...   
999913        1210            MQ       4693  ...    NaN      NaN          1   
999919        1210            MQ       4693  ...    NaN      NaN          1   
999961        1630            MQ       4694  ...    NaN      NaN          1   
999971        1415            MQ       4694  ...    NaN      NaN          1   
999999        2005            MQ       4695  ...    NaN      NaN          1   

        CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
178                    A         0           NaN          NaN      NaN   
373                    A         0           NaN          NaN      NaN   
399                    A         0           NaN          NaN      NaN   
401                    C         0           NaN          NaN      NaN   
415                    A         0           NaN          NaN      NaN   
...                  ...       ...           ...          ...      ...   
999913                 A         0           NaN          NaN      NaN   
999919                 B         0           NaN          NaN      NaN   
999961                 B         0           NaN          NaN      NaN   
999971                 B         0           NaN          NaN      NaN   
999999                 B         0           NaN          NaN      NaN   

        SecurityDelay  LateAircraftDelay  
178               NaN                NaN  
373               NaN                NaN  
399               NaN                NaN  
401               NaN                NaN  
415               NaN                NaN  
...               ...                ...  
999913            NaN                NaN  
999919            NaN                NaN  
999961            NaN                NaN  
999971            NaN                NaN  
999999            NaN                NaN  

[32133 rows x 29 columns]

INTRODUCCIONA LA LIBRERIA NUMPY

In [45]:
import numpy as np

In [47]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [48]:
valoraciones[0][1]

7

In [53]:
valoraciones2 = valoraciones = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])

In [54]:
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [55]:
valoraciones2[0,1,2]

5

In [62]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
valoraciones2 + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [64]:
np.max(valoraciones2)

10

In [65]:
np.mean(valoraciones2, axis=1)

array([[5. , 6. , 6.5, 3.5],
       [5. , 7.5, 7.5, 4. ],
       [9. , 8.5, 9.5, 5.5]])

In [70]:
np.random.rand(2,2)

array([[0.17240201, 0.11149025],
       [0.73546893, 0.44368597]])