In [1]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('base_datos_2008.csv', nrows= 1000000)
df = df[["ArrDelay","DepDelay","Distance","AirTime"]].dropna()

In [5]:
X_scaled = preprocessing.scale(df) #Escala los datos
X_scaled

array([[-0.62279474, -0.11867759,  0.21368671,  0.22947535],
       [-0.22769689,  0.1781292 ,  0.21368671,  0.18373789],
       [ 0.06862649, -0.11867759, -0.33122127, -0.38035736],
       ...,
       [-0.0795352 , -0.55039656,  0.3873184 ,  0.35144189],
       [-0.4005522 , -0.38850194,  0.3873184 ,  0.19898371],
       [-0.62279474, -0.46944925,  0.3873184 ,  0.09226299]])

In [7]:
X_scaled.std(axis=0)

array([1., 1., 1., 1.])

In [8]:
df.iloc[2]

ArrDelay     14.0
DepDelay      8.0
Distance    515.0
AirTime      76.0
Name: 2, dtype: float64

In [9]:
X_scaled[2]

array([ 0.06862649, -0.11867759, -0.33122127, -0.38035736])

In [10]:
#Otro tipo de escalado
min_max_scaler = preprocessing.MinMaxScaler([0,10]) #Especifica el rango de valores que quiere que tenga
x_train_minmax = min_max_scaler.fit_transform(df) 
x_train_minmax

array([[0.47648515, 0.69013112, 1.59173755, 1.79844961],
       [0.57549505, 0.76604555, 1.59173755, 1.75193798],
       [0.64975248, 0.69013112, 0.99432969, 1.17829457],
       ...,
       [0.61262376, 0.57971014, 1.78209802, 1.92248062],
       [0.53217822, 0.62111801, 1.78209802, 1.76744186],
       [0.47648515, 0.60041408, 1.78209802, 1.65891473]])

In [13]:
#Otro tipo
df1 = pd.read_csv("base_datos_2008.csv", nrows=100)
pd.get_dummies(df1["Origin"]) #Transforma la columna Origin para cada una de las categorias

IAD  IND  ISP  JAN  JAX  LAS
0     1    0    0    0    0    0
1     1    0    0    0    0    0
2     0    1    0    0    0    0
3     0    1    0    0    0    0
4     0    1    0    0    0    0
..  ...  ...  ...  ...  ...  ...
95    0    0    0    0    0    1
96    0    0    0    0    0    1
97    0    0    0    0    0    1
98    0    0    0    0    0    1
99    0    0    0    0    0    1

[100 rows x 6 columns]